### ISSUE TITLE
Practice App: Implementing the API for Rate Article

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#100]
## Description
The endpoints were determined in [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2).  Rate-article functionalities will be implemented.

We have distributed the tasks among 12 group members and my main responsibility is to implement comment-info endpoint and API.

Together in the Meeting 10.2, as stated in issues [#78](https://github.com/bounswe/bounswe2022group5/issues/78) and  [#79](https://github.com/bounswe/bounswe2022group5/issues/79) , we have decided on the models and pushed them to our GitHub.

Main functionality of the rate-post part of the project is that,
- Getting number of upvotes and downvotes of an article with a specific ID as the GET part of the API
- Upvoting or downvoting an article with a specific id as the POST part of the API

### Details of the rate-article API:
- [x] Check whether the given data is valid or not.
- [x] Check whether the article with the given article-id exists.
- [x] Updating and saving votes of articles, or getting votes of articles.
- [x] Success or Error Response.

Requests and responses will be documented by using Postman.

**Task Deadline: 14.05.2022 16:00 (Deadline Extended)**

**Review Deadline: 14.05.2022 20:00 (Deadline Extended)**

**Reviewers: @enginoguzhansenol @busetolunay**

**Comment by bbenginbestas** [comment]
Everything in the list has been done. Closing the issue.
