### ISSUE TITLE
Practice-App: Writing all unit tests for Post app

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#101]
**Description:**

The tests will be implemented for the Post app of the Practice-App using the TestCase library from django.test. Find more about Post from the issue #83.

**Details for tests and *todo's*:**
- [x] Write tests for urls.
- [x] Write tests for views.
- [x] Write tests for models.
- [x] Write tests for forms.

**Reviewers:** @mehmetemreakbulut @canberkboun9 

**Task Deadline:** 14.05.2022 16:00
**Review Deadline:** 14.05.2022 20:00

**Comment by yavuuzsameet** [comment]
TestCases are implemented and pushed. Need review.

**Comment by yavuuzsameet** [comment]
Test cases are updated by the new merge #136.
