### ISSUE TITLE
Practice App: Implementing API for User - Unit Tests

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#104]
**Description:**

* The tests will be implemented for the User APIs of the Practice-App. 
* TestCase library from django.test. 
* Detailed explanation is avaliable in #81 and #87.

**Details for tests and *todo's*:**
- [x] Write tests for urls.
- [x] Write tests for views.
- [x] Write tests for models.
- [x] Write tests for forms.

**Reviewers:** @kardelendemiral @busetolunay  

**Task Deadline:** 14.05.2022 16:00
**Review Deadline:** 14.05.2022 20:00

**Comment by mehmetemreakbulut** [comment]
* Unit tests are done. 
* django.test library is used for testing process.
* test_models.py, test_urls_py, tests_views.py are created in the tests folder of "user" app.
* We don't use the real database for testing. Mocking database "deafult".
* After testing, test database is destroyed.
* Latest version is pushed. Find the PR #118
