### ISSUE TITLE
Practice App: Implementing API for Article

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#105]
## Description
According to the endpoints we determined in the [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2), _article/_ endpoint should be implemented (Task 16-17).

We have distributed the tasks among 12 group members and my main responsibility is to implement comment-info endpoint and API.

During the meeting, as stated in issues [#78](https://github.com/bounswe/bounswe2022group5/issues/78) and  [#79](https://github.com/bounswe/bounswe2022group5/issues/79) , we have decided on the models and pushed them to our GitHub.

Main functionality of the article/_ endpoint of the project is that,
- Getting all articles as the GET part of the API
- Posting an article as the POST part of the API

### Details of the rate-article API:
- [ ] Check whether the given data is valid or not.
- [ ] Getting all articles as the GET part of the API
- [ ] Posting an article as the POST part of the API
- [ ] Success or Error Response.
- [ ] Postman Test.
- [ ] Saving to Postman.
- [ ] Documentation.

Requests and responses will be documented by using Postman.

**Task Deadline: 14.05.2022 16:00**

**Review Deadline: 14.05.2022 20:00**

**Reviewers: @makifyilmaz  @bbenginbestas

**Comment by canberkboun9** [comment]
- An initial commit has been made and a [pull request](https://github.com/bounswe/bounswe2022group5/pull/129) merged. 
- A little modification is implemented in views.py but a commit was not sent yet.
- A new postman tests have been conducted and a Collection has been created.
- [Documentation](https://documenter.getpostman.com/view/12691360/UyxkmmMA) has been published.
- The Collection can be accessed via:
- 
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/98909e1006dbfc8ab0bc)

**Comment by canberkboun9** [comment]
Extension of this issue is #140, I am closing this issue.
