### ISSUE TITLE
Practice App: Implementing the API for Rate Comment

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#109]
**Description**
According to the endpoints that determined by the group in the [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2), rate-comment functionalities should be implemented.

We have distributed the tasks among 12 group mates and my main responsibility is to implement rate-comment endpoint and API.

Together in the Meeting 10.2, as stated in issues [#78](https://github.com/bounswe/bounswe2022group5/issues/78) and [#79](https://github.com/bounswe/bounswe2022group5/issues/79), we have decided on the models and pushed them to our GitHub.

Main functionality of the rate-comment part of the project is that,

Getting number of upvotes and downvotes of a comment with a specific ID as the GET part of API
Upvoting or downvoting a comment with a specific id as the POST part of API

**Details of the rate-comment API:**

- [x]  Check whether the given data is valid or not.
- [x]  Check whether the comment with the given comment-id exists.
- [x]  Updating votes or getting votes.
- [x]  Success or Error Response.
- [ ]  Documentation.
- [ ]  Postman Test.
- [ ]  Saving to Postman

Requests and responses will be documented by using Postman.

**Task Deadline:** 14.05.2022 16:00
**Review Deadline:** 14.05.2022 20:00

**Reviewers:** @bbenginbestas @yavuuzsameet

**Comment by yavuuzsameet** [comment]
@enginoguzhansenol the deadline for the task is passed, but since the instructor gave 3 days of extension to the initial submission deadline, this task's deadline can be extended too. However, it would be better to start working on with the creation of a new branch for your work.
