### ISSUE TITLE
Revising the Meeting Notes Template

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#168]
**Description:**

 - Task 9. [Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1)

Revising the [Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template). Editing the page accordingly. Uploading the [Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1) according to the new template.

**Todo's:**
- [x] Changing the Action Items columns.
- [x] Inserting info in the Meeting Information into a nice looking table.
- [x] Deleting the Duration.

**Reviewers:** @palahb 

**Task Deadline:** 10/10/2022 14:00
**Review Deadline:** 10/10/2022 19:00

(This issue will be updated according to the new Issue Template.)

**Comment by canberkboun9** [comment]
Done all three parts, additional changes may be added upon review.

**Comment by palahb** [comment]
[Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1) page looks quite nice. Can you please update the [Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template) page?

**Comment by canberkboun9** [comment]
[Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template) page is updated. 

Next Meeting Information is edited. It now looks like the meeting information part, it's a table. 

[Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1) page is edited accordingly.

I think we can close the issue as there is not any new changes suggested or needed.
