### ISSUE TITLE
Revising the Scenarios and Mockups, making adjustments needed.

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#170]
**Description:**

*It's been a long time since scenarios and mockups were created. Considering that our knowledge and skills have changed since then, it seems that we need to revise them again. It is also necessary to increase its readability.*

**Todo's:**
- [x] *Revising the 3 scenarios and mockups we created*.
- [x] *Adding new things if needed*.
- [x] *Putting them all in one format*.

**Reviewer:** *@yavuuzsameet*   

**Task Deadline:** 10.10.2022 14:00  
**Review Deadline:** 10.10.2022 19:00

**Comment by mehmetemreakbulut** [comment]
- Scenarios were revised. 
- There were some differences in the scenario format Fixed.
- Preconditions and goals were not very clear. Adding some new preconditions and goals to the scenarios
- Grammar errors fixed
- See:
   - [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1)
   - [Scenario 2](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2)
   - [Scenario 3](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-3)

**Comment by yavuuzsameet** [comment]
I compared your revision with the previous one, and I see that all of them are in the same format as you mentioned. Adding a new precondition to the second scenario is helpful. Thanks for your work. I am now closing the issue.
