### ISSUE TITLE
Updating Wiki Home Page

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#171]
**Description:**

*Wiki Home Page should be updated as we are starting our new semester and starting to implement our project.*

***Todo's*:**
- [x] *Getting the new photo of us from @bbenginbestas*.
- [x] *Adding this new photo of us that we were taken in [Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1)*.
- [x] *Revising and updating other sections if needed*.

**Reviewer:** *@enginoguzhansenol* 

**Task Deadline:** 10.10.2022 14:00  
**Review Deadline:** 10.10.2022 19:00

**Comment by palahb** [comment]
The wiki home page is updated by help of @bbenginbestas. Need @enginoguzhansenol’s review before closing the issue.

**Comment by enginoguzhansenol** [comment]
The group photo looks perfect. Thank you @palahb and @bbenginbestas. 
We can add the Issue Template and Meeting Notes Template to the wiki home page. Also, Class Diagram and Use Case Diagrams are missing in the Practice App section. After adding these pages, we can close this issue.
Thank you both for your collaboration.
