### ISSUE TITLE
Updating Wiki Sidebar

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#172]
**Description:**

*Wiki sidebar should be updated as it was discussed in the [Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1).*

***Todo's*:**
- [x] *A "former members" section will be added*.
- [x] *The meetings from CMPE352 and CMPE451 will be separated*.
- [x] *New members' wiki pages will be added to the sidebar*.

**Reviewer:** *@canberkboun9* 

**Task Deadline:** 10.10.2022 14:00
**Review Deadline:** 10.10.2022 19:00

**Comment by irfanbozkurt** [comment]
I added mine!

**Comment by kardelendemiral** [comment]
All three tasks are completed. I can make further updates after your review @canberkboun9 .

**Comment by canberkboun9** [comment]
Great job, thanks!
I think new additions for meeting notes made the Sidebar more usable as they were occupying a lot of space.
Links work correctly, if a new suggestion comes or a need for a change in Sidebar comes up, we can open the issue, but for now, we can close it.
