### ISSUE TITLE
Listing questions and clarifications to refine the Requirements

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#173]
**Description:**

*Requirements should be revised before starting the implementation of the project. Everyone can share ideas about refinements by commenting on this issue.*

***Todo's*:**
- [x] *Gathering ideas from the group members.*
- [x] *Listing possible changes that can be made to refine the requirements.*
- [x] *Communicating with the customer about the **reviewed** list.*

**Reviewer:** *@burakmert236, @irfanbozkurt* 

**Task Deadline:** 09.10.2022 20:00  
**Review Deadline:** 10.10.2022 22:00

**Comment by enginoguzhansenol** [comment]
I noted some changes that can be made to certain requirements. Also found new requirement ideas to the relevant sections.

1. **1.1.1.1.9 Registered users shall register their unique e-mail to the system while registering.
1.1.1.1.10 Registered users shall confirm their e-mail addresses via e-mail authentication while registering**
We can remove the unique e-mail confirmation since we are also confirming with the phone number.

2. **1.1.1.2.1 Members shall be able to sign in to the system using their nickname, e-mail or phone number, and their password.
1.1.1.2.2 Doctors shall be able to sign in to the system using an e-mail or phone number and their password.**
We can combine these two requirements by using "Registered Users" instead of "Doctors" and "Members".

3. **1.1.1.2.3 Registered users shall be able to sign in if they forgot their password with forgot password mechanism.**
The requirement can be changed and moved to the Security section since it is not a part of the Sign-in

4. **1.1.2.3.6 Article-owners shall be able to edit articles they created.**
Members should not edit their articles without the approval of a  doctor.

5. **1.1.1.3.7 Doctors shall have icons in their profiles showing that their accounts are verified.**
We can remove this icon requirement since doctors cannot have an unverified account.

6. **Sign-in & Sign-out**
There can be a new requirement for "Remember me" for users that signed in before.

7. **Chatbot**
We can use the chatbot while registering to the system.

8. **Notifications**
"Registered users shall get a notification when other users create a post or created an article about the tags and categories that they followed.", and "Doctors shall get a notification when members proposed an article in their category." can be added to the Notifications Requirements.

**Comment by irfanbozkurt** [comment]
Here are my thoughts on proposals of @enginoguzhansenol 

- Using phone number is extra overhead, and it doesn't prove any kind of identity. We should get rid of it and only stick to e-mail addresses, also to avoid SMS charges.
- All users will have e-mail and password, but only Member users will have usernames. Therefore, member users can log-in via e-mail or username, but doctors will have to login using their e-mails.

Apart from these, I think proposals **3,4, and 5** are valid & necessary.

**Comment by irfanbozkurt** [comment]
Here are some questions I think we should clarify with the TA in the next meeting:

1. What should "acivity history" include exactly?
	CRUD'ing posts & comments
	CRUD'ing articles
	Upvotes & Downvotes
  Is this functionality mandatory?

2. Is it mandatory to create an "activity history" for admins?

3. Is a "chatbot" mandatory? If so, what exactly should it do?

4. Is it mandatory to create a "search history" for the users?

5. Is it okay if we do not use phone numbers and only go with
e-mail addresses for authentication? Doctors will upload a document 
to prove their identity & profession.

**Comment by Oozankilic** [comment]
I realized some possible improvements additional to @enginoguzhansenol has mentioned above

1. **1.1.1.8 Registered users shall confirm their phone number via text message authentication while registering.
1.1.1.1.10 Registered users shall confirm their e-mail addresses via e-mail authentication while registering.**
We can eliminate the phone authentication at sign up page and just use email authentication. Two authentications can be a burden to new comers. If telephone authentication is needed at some point, then it can be asked.

2. **1.2.3.3 Articles created by members shall need to be reviewed and approved by a doctor to be published.
1.1.2.3.5 Article-owners shall add a title to their articles.
1.1.2.3.6 Article-owners shall be able to edit articles they created.
1.1.2.3.7 Article-owners shall be able to delete articles they created.**
Member can edit articles after the articles are approved and published. But these changes are not controlled by a doctor. This situation can results non scientific articles in the application. The changes at articles also can be reviewed by a doctor.

**Comment by irfanbozkurt** [comment]
Here are some more remarks from my side:

- We should avoid "Discussion thread" terminology, because it doesn't add any semantic meaning on top of a Post. Comments strictly belong to a Post anyway, so why make up a new term when we can just use "Post"?  I think it's very likely to create confusion, so we should stay at a simpler level of abstraction.

And, some proposals:

### 1.1.1.2 Sign-in & Sign-out
* **1.1.1.2.1** Members shall be able to sign-in to the system using their nickname or e-mail, and their password.
* **1.1.1.2.2** Doctors shall be able to sign-in to the system using e-mail and their password.
* **1.1.1.2.3** Registered users shall be able to sign-in if they forgot their password with _forgot password_ mechanism.
* **1.1.1.2.4** Registered users shall be able to sign-out.
<br>


### 1.1.2.3 Articles
* **1.1.2.3.1** Doctors shall be able to create articles.
* **1.1.2.3.2** Members shall be able to propose articles.
* **1.1.2.3.3** Articles proposed by members shall be reviewed and approved by a doctor before being published.
* **1.1.2.3.4** Registered users shall add a title and a body when creating an article.
* **1.1.2.3.5** Registered users shall be able to add tags when creating an article.
* **1.1.2.3.6** Registered users shall be able to edit & delete their articles.
* **1.1.2.3.7** Article changes proposed by members (to their own articles) shall be reviewed and approved by a doctor before being published.
* **1.1.2.3.8** Users shall be able to read any article.
<br>

### 1.1.4.1 Searching 
* **1.1.4.1.1** Users shall be able to use the search engine to list posts, articles, or registered users.
* **1.1.4.1.2** Search engine shall support full-text search for titles & bodies to list corresponding posts or articles.
* **1.1.4.1.3** Search engine shall support keyword-based search for tags, category, author (username or name) to list corresponding posts or articles.
* **1.1.4.1.4** Search engine shall support date-based search to list corresponding posts or articles.
* **1.1.4.1.5** Search engine shall support geolocation-based search to list corresponding posts.
* **1.1.4.1.6** Search engine shall support keyword-based search for username or legal name to list corresponding members or doctors.

**Comment by palahb** [comment]
Nice contributions. All of these suggestions make sense to me. 

A contribution that I can add can be about *referencing a post or a comment*. We can define an *ID number* for every post and comment, and a registered user can refer to a post or a comment in their posts and comments by using their IDs. By that way, we can avoid using nested comments. For this, maybe we can add a requirement in **1.1.2.1 Forum** section like:
- **1.1.2.1.x** Registered users shall be able to refer to a post or a comment by referencing the ID of this post or comment.

**Comment by enginoguzhansenol** [comment]
Since not enough people commented, a clear list could not be created.  At the next meeting, everyone's thoughts will be collected and a suitable list will be created.

**Comment by canberkboun9** [comment]
We could maybe combine category and tag.

Glossary:
Chatbot: A software application used to conduct an on-line chat conversation with users.

We could clarify this definition when chatbot requirements are completed.
