### ISSUE TITLE
Preparing our Discord channel for the new semester

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#175]
**Description: Some minor changes will be made for discord to be a better environment for our studies.**

*Since we have new members for our group, they will be invited to our Discord channel, also for a better environment, new text channels and new voice channels will be created.*

***Todo's*:**
- [x] *Inviting our new members to our discord channel*.
- [x] *Creating voice channels for backend, frontend and mobile development sections*.
- [x] *Creating text channels for backend, frontend and mobile development sections*.

**Reviewer:** @palahb

**Task Deadline:** 10.10.2022 23:59  
**Review Deadline:** 11.10.2022 14:00

**Comment by palahb** [comment]
Our discord channel seems ready for the new semester. Thank you Bengin!
