### ISSUE TITLE
Adding new tabs to the sidebar for Backend, Frontend and Mobile Team Meetings 

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#176]
**Description:**

*3 new tabs will be added under the CMPE452 Meetings section in sidebar for Backend, Frontend and Mobile team meetings.*

***Todo's*:**
- [x] *Backend team meetings section will be added*.
- [x] *Frontend team meetings section will be added*.
- [x] *Mobile team meetings section will be added*.

**Reviewer:** *@canberkboun9* 

**Task Deadline:** 17.10.2022 14:00  
**Review Deadline:** 17.10.2022 20:00

**Comment by canberkboun9** [comment]
Thank you Kardelen! I have a suggestion. I think that if the team meeting sections were collapsible just like "Meeting Notes From CMPE451", it would be easier to access each meeting note of a team from there. 

For example, instead of this:

##### Team Meetings
- [Backend Team Meetings](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Team-Meetings)
- [Frontend Team Meetings](https://github.com/bounswe/bounswe2022group5/wiki/Frontend-Team-Meetings)
- [Mobile Team Meetings](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Team-Meetings)

We could do this:

##### Team Meetings
<details>

<summary> Backend Team Meetings </summary>

</details>
<details>

<summary> Frontend Team Meetings </summary>

</details>
<details>

<summary> Mobile Team Meetings </summary>

</details>

**Comment by kardelendemiral** [comment]
Thank you for the suggestion! I changed the structure as you recommended. I think it got better in terms of visuals also. I would like to hear if you have any other suggestions. If not so, we can close the issue.

**Comment by canberkboun9** [comment]
Thank you! I have another ideas I'd like to share:

- If the "General Meetings" were on the "Team Meetings", it may looked better. Also, if we use lesser # in the titles and making the titles bigger, it would look less confusing.

For example, 
### Team Meetings
instead of:
##### Team Meetings

Also,
- We could take one # off from [Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template) and [Meetings](https://github.com/bounswe/bounswe2022group5/wiki/Meetings), it would look more consistent with the change in *Team Meetings* title.

**Comment by kardelendemiral** [comment]
Thanks again, for all the good suggestions. I think I made the necessary modifications if I understood what you meant correctly. Can you check if it looks ok now? @canberkboun9

**Comment by canberkboun9** [comment]
Thank you Kardelen! It's perfect!

We may close the issue.
