### ISSUE TITLE
Uploading Customer Meeting 5 Notes

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#179]
**Description:**

*The notes of Customer Meeting 5 will be uploaded to our wiki page.*

***Todo's*:**
- [x] *Creating a new page and uploading the notes there.*
- [x] *Adding the page to the wiki sidebar.*
- [x] *Adding the page to the Customer Meetings page.*

**Reviewer:** *@bbenginbestas , @mehmetemreakbulut * 

**Task Deadline:** 17.10.2022 17:00  
**Review Deadline:** 18.10.2022 12:00

**Comment by enginoguzhansenol** [comment]
The notes of [Customer Meeting 5](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-5) are uploaded to the group wiki page. The wiki sidebar and [Customer Meetings](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meetings) page are both also updated. Need review before closing.

**Comment by mehmetemreakbulut** [comment]
Meeting Notes seem very well. Also, the sidebar was updated successfully. All 3 tasks are done. We can close the issue.
