### ISSUE TITLE
Revising the Class Diagram

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#181]
***Description*:**

[The Class Ciagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram) that was prepared last semester should be updated according to the changes made in the [Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements).

***Todo's*:**
- [x] Detect the changes in the requirements that lead to changes in the [Class Diagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram).
- [x] Update the [Class Diagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram) according to these updates.
- [x] Upload the new version to the repository.

***Reviewers*:** @burakmert236 , @irfanbozkurt 

***Task Deadline*:** 17.10.2022 23:00  
***Review Deadline*:** 18.10.2022 12:00

**Comment by palahb** [comment]
Some changes in the [Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements) that can lead some changes in the [Class diagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram):
- Activity history will include posts, comments and upvotes/downvotes of a user.
- Users will register to the system using only e-mail authentication.
- Only doctors shall be able to create articles.

**Comment by oguzhandemirelx** [comment]
I added validateEmail, validateCaptcha, getMyUpvotes, getMyPosts, getMyComments and getMyArticles functions to the necessary classes.

**Comment by palahb** [comment]
- Removed _proposeArticle_ function from __Member__ class.
- Removed _approveArticle_ function from __Doctor__ class.
- Added _createArticle function_ to the __Doctor__ class.
- Removed the arrow directed from __Member__ to __Article__.

**Comment by oguzhandemirelx** [comment]
Uploaded the new class diagram to [Class Diagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram) wiki page.
