### ISSUE TITLE
Rearranging the Repo Structure and Branches For Collaborative Work

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#188]
***Description*:**

We need to prepare our repository to work on our project collaboratively. Frontend and backend teams created completely separate branches to work, but we decided that this is not a proper way of organizing our repo. Instead, creating a branch from the master branch to set up a directory structure for collaborative work among all teams. While creating new branches, a branching convention like we decided [here](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2#branching-conventions) can be followed for now. After these changes, resulted directory tree should be like this:
```
bounswe2022group5
│
│
└──app
│  │
│  └──backend
│      │   ...
│   └──frontend
│      │   ...
│   └──mobile
│      │   ...
│   
└──practice-app
│  │   ...
│
└──deliverables
│  │   ...
│  
│  README.md
│  .gitignore 
```
Every team can then work on their own folders.

***Todo's*:**
- [x] Deleting inactive branches
- [x] Creating a branch to set up a directory for collaborative work
- [x] Rewriting README.md file
- [x] Moving folders in frontend branch to newly created directory structure (@burakmert236)
- [x] Moving folders in backend branch to newly created directory structure (@mehmetemreakbulut)

***Reviewers*:** @oguzhandemirelx, @kardelendemiral 

***Task Deadline*:** 23.10.2022 12:00  
***Review Deadline*:** 23.10.2022 15:00

**Comment by palahb** [comment]
I deleted inactive branches that we created while implementing practice-app.

**Comment by palahb** [comment]
I made the necessary changes and created a branch, opened a pull request (#189). After a review, it can be merged. 

After that, files in the branches created for frontend and mobile development can be moved to the current folder structure. If you do so, please also do not forget deleting these branches also. @burakmert236 @mehmetemreakbulut

**Comment by mehmetemreakbulut** [comment]
* I pushed the initial backend project to the branch. Also deleted the backend branch from the repository.
* See: [Initial Backend Project](https://github.com/bounswe/bounswe2022group5/tree/app/enhancement/arranging-repo-%23188/app/backend)

**Comment by burakmert236** [comment]
I pushed frontend folder into branch (app/enhancement/arranging-repo-#188). Since all tasks are done, I am closing the issue.
