### ISSUE TITLE
Creating initial mobile app structure

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#190]
***Description*:**

Initial flutter mobile app structure should be created and pushed to the repository.

***Todo's*:**
- [x] Initial screens should be created.
- [x] Initial model structure should be created. (Later it can be changed according to backend team's decisions.)
- [x] This structure should be pushed to the repo.

***Reviewers*:** @enginoguzhansenol 

***Task Deadline*:** 23.10.2022 14:00  
***Review Deadline*:** 23.10.2022 15:00

**Comment by palahb** [comment]
- Initial flutter app structure was created.
- Initial model structure was created.
- Initial screens were created.
- Theme of the app was added.
- Some dependencies were added. Do not forget running `flutter pub get` before working on the project.
