### ISSUE TITLE
Choosing / Deploying a Database Service

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#194]
***Description*:**

Our application will use one RDBMS for simplicity.
This database server is agreed to be PostgreSQL, and it needs to be deployed to AWS on top of an EC2 instance.

***Todo's*:**
- [x] Create an AWS account for everyone (with free tier)
- [x] Provision an EC2 instance
- [x] Make EC2 instance publicly accessible
- [x] Deploy PostgreSQL to that machine
- [x] Test connection to the database

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by irfanbozkurt** [comment]
DB instance is deployed and details are as follows:
- Public DNS: ec2-100-24-23-233.compute-1.amazonaws.com
- Port: 5432
- Database name: app
- Database username: postgres
- Database password: refer to WhatsApp

**Comment by canberkboun9** [comment]
Looks good, we checked it is working.
Closing the issue.
