### ISSUE TITLE
Create Initial Tables in the Database

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#199]
***Description*:**

Database deployment is completed, and now the database schema should be created, and database connectivity (via model classes) must be tested.

***Todo's*:**
- [x] Create initial tables as described in [Initial Tables @Backend meeting 1.2](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.2#discussion)
- [x] Create model classes in the application
- [x] Make sure application connects to the database and model classes are available for use

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by irfanbozkurt** [comment]
Hi all, 

After creating the model classes, I actually ended up writing some **unit tests** for them.

I hope it'll prevent confusions and errors in the future.

Refer to [my commit](https://github.com/bounswe/bounswe2022group5/commit/ad074e34792c20571b8eaa2e768d1037c008ab68) 
Find model classes under /app/backend/backend/models.py (ALL of them)
Find tests under /app/backend/tests (ALL of them)

I'll keep writing a couple of more tests before the PR

**Comment by irfanbozkurt** [comment]
My efforts can now be reviewed!

**Comment by canberkboun9** [comment]
Thank you! Checked the code and reviewed the PR.

**Comment by irfanbozkurt** [comment]
[The PR](https://github.com/bounswe/bounswe2022group5/pull/203) is now closed and changes are merged!
