### ISSUE TITLE
Creating 'authentication' module inside the project

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#204]
***Description*:**
- To identify the user of the coming request and manage authentication, an 'authentication' module inside the Django project is necessary. Also, implementing auth as a different module helps us to isolate the functionalities and some middleware. 

***Todo's*:**
- [x] Creating an authentication module inside the project.
- [x] Changing configs to use the authentication module.
- [x] Setting up models, constants, and utils related to authentication. 

***Reviewer*:** @oguzhandemirelx  

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by mehmetemreakbulut** [comment]
* Tasks are done and the authentication module is created. TokenAuth will be implemented #205 
* PR is created #208

**Comment by oguzhandemirelx** [comment]
I examined your PR, all things are nicely done. Merged your pull request, we can close this issue.
