### ISSUE TITLE
Implementing Token Authentication with Django Rest Framework

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#205]
***Description*:**
- Token authentication refers to exchanging a username(email) and a password for a token that will be used in all subsequent requests so to identify the user on the server side.
- The token authentication works by providing tokens in exchange for exchanging usernames and passwords.

***Todo's*:**
- [x] Configuring authentication classes about Token Authentication in settings.py
- [x] Connecting Token authentication class with User abstract class.
- [ ] Implementing token generators by Django Signals
- [x] Implementing obtain_token endpoint which will be used for further tasks.

***Reviewer*:** @irfanbozkurt 

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by mehmetemreakbulut** [comment]
* All tasks except the token generator were done. It is not necessary. 
* Authentication module hasn't been implemented successfully because the Login and Signup documentation is not ready. See #206 , #201

**Comment by irfanbozkurt** [comment]
Your changes for authentication looks good to me.

Will we be able to use our "User" class still, or, will Django create another table for this purpose? I'm asking because I realized a new table "auth_user" in the database.

Thanks
