### ISSUE TITLE
Implementing Login and Signup Endpoints

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#218]
***Description*:**

Documentation is ready on the [API Documentation Signup](https://github.com/bounswe/bounswe2022group5/wiki/Signup-API-Documentation) and [API Documentation](https://github.com/bounswe/bounswe2022group5/wiki/Login-API-Documentation). 
Based on this documentation, it is necessary to implement the signup and login endpoints to be ready.

***Todo's*:**
- [x] Implementing Signup Endpoint.
- [x] Implementing Login Endpoint.
- [x] Writing unit test of these functionalities.

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 27/10/2022 12:00
***Review Deadline*:** 27/10/2022 18:00

**Comment by mehmetemreakbulut** [comment]
- Endpoints are created. Tested via Postman.
- I added User Manager to User Model because we created a custom user model. 
- Validations added to serializers.
- Tests are implemented for functionalities added.

- See #219

**Comment by oguzhandemirelx** [comment]
Thanks for your effort Emre. I think we can also write error responses for these endpoints. It helps our frontend and mobile teams to show error messages on the page.
