### ISSUE TITLE
Dockerization and Deployment of Backend

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#220]
***Description*:**

Current state of back-end should be deployed to AWS after being dockerized.

***Todo's*:**
- [x] Dockerize back-end
- [x] Deploy on an AWS EC2 instances
- [x] Make sure endpoints are accessible

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 26/10/2022 23:00
***Review Deadline*:** 27/10/2022 12:00

**Comment by irfanbozkurt** [comment]
Please refer to [this commit](https://github.com/bounswe/bounswe2022group5/commit/148c2917440523a435e63acd38f835d7364ddfe3) for dockerization.

The README isn't ready yet.
To dockerize and run it in a container locally:

- docker compose build
- export DATABASE_HOST=<refer_to_whatsapp>
- export DATABASE_PW=<refer_to_whatsapp>
- docker-compose up

If these environment variables are missing on your machine, you cannot run the container.

Later today, I'll provision an EC2 instance to run this image on.

CD automation must wait a little.

Thanks!

**Comment by irfanbozkurt** [comment]
For further reference, I'm giving some details here:

I created a **launch template** which pulls our repository, dockerizes the image, and runs the image automatically.
This was possible because of the **user-data** feature of EC2: it runs a bunch of bash script when you provision an instance.

Now the application can be accessed via:
[http://ec2-3-87-119-148.compute-1.amazonaws.com:8000/admin](http://ec2-3-87-119-148.compute-1.amazonaws.com:8000/admin)

This dummy deployment should be enough to satisfy the customer for the upcoming meeting.

Please refer to [my pull request](https://github.com/bounswe/bounswe2022group5/pull/231) for the code of dockerization.

**Comment by mehmetemreakbulut** [comment]
Everything seems very well. We also tested the deployment and the backend is accessible for remote connections.
