### ISSUE TITLE
Connecting all mobile pages

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#229]
***Description*:**
All mobile pages implemented so far should be connected by adding links between them. This will be implemented in Mobile Meeting 2 with all teammates.

***Todo's*:**
- [x] Login page should be the initial page when the app is opened.
- [x] From login page, there should be a connection to Signup page.
- [x] From login page, there should be a connection to Home page (for unregistered users.)
- [x] From Signup page, there should be a connection to Login page (if the user does not want to sign up)
- [x] From the home page, there should be a connection to the Profile page
- [x] From the Profile page, there should be a connection to the Home page
- [x] From the Home page, there should be a connection to Login page (for logging out)

***Reviewer*:** @enginoguzhansenol, @bbenginbestas 

***Task Deadline*:** 29.10.2022 10:00  
***Review Deadline*:** 29.10.2022 12:00

**Comment by palahb** [comment]
All necessary connections are made in the [Mobile Meeting [2].](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-2) with all of our teammates. Since we do not have access to backend right now, we cannot implement the following connections at the moment:

- From login page, there should be a connection to Home page (for registered users after successfully logging in.)
- From Signup page, there should be a connection to Login page (after succesfully signing up.)

These will be implemented when the backend is deployed.
