### ISSUE TITLE
Creating upper layout (top bar) of website.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#235]
***Description*:**

Creating the upper layout of the homepage. Which is the one that will be used as a common component among all the website.

***Todo's*:**
- [x] Creating and aligning the top bar.
- [x] Inserting search field, login-signup buttons and logo in it.
- [x] Needs to show signup/login or logout button with respect to the login information of the user.
- [x] Login / Logout Functionality needs to be added.

***Reviewer*:** @burakmert236 

***Task Deadline*:** 29.10.2022 23:00
***Review Deadline*:** 30.10.2022 12:00

**Comment by Keremgunduz7** [comment]
Could you please review the code, for now the logout functionality is not implemented.
I will add it afterwards.

**Comment by burakmert236** [comment]
I ran and reviewed the code, it works fine. Logout functionality can be implemented after all branches are merged. I also merged the related pull request, therefore we can also close this issue.

**Comment by Keremgunduz7** [comment]
Thanks for the comment, Has implemented logout functionality into the button.
also gathered reviews in the related [PR](https://github.com/bounswe/bounswe2022group5/pull/256).
Closing the issue.
