### ISSUE TITLE
Adding an API service class to the mobile app

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#240]
***Description*:**

To add the functions handling the API calls, an API service class should be added to the mobile application. This will be done in [Mobile Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-3)

***Todo's*:**
- [x] An API service class will be added.
- [x] A function handling the login API call will be added.
- [x] A function handling the register API call will be added.
- [x] A function handling the logout API call will be added.

***Reviewers*:** @bbenginbestas , @palahb 

***Task Deadline*:** 29.10.2022 17:00  
***Review Deadline*:** 29.10.2022 23:00

**Comment by kardelendemiral** [comment]
The necessary class and the functions are added with the [Pull request #244](https://github.com/bounswe/bounswe2022group5/pull/244). We can close the issue after one the reviewers merges the PR.

**Comment by palahb** [comment]
We implemented this API service methods and checked their functionality together in [Mobile Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-3).
