### ISSUE TITLE
Fix the authentication_classes bug & deploy new version

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#246]
***Description*:**

There's a small bug (a forgotten import statement) in our [latest PR](https://github.com/bounswe/bounswe2022group5/pull/242).
This bug must be fixed and new version must be deployed to AWS.

As this is a hotfix issue that must be performed quickly, I'll be reviewing my own work.

***Todo's*:**
- [x] Fix the bug
- [x] Test if app works
- [x] Deploy to AWS

***Reviewer*:** @irfanbozkurt  

***Task Deadline*:** IMMEDIATE

**Comment by irfanbozkurt** [comment]
See my [pull request](https://github.com/bounswe/bounswe2022group5/pull/247).

**Comment by irfanbozkurt** [comment]
Deployment completed.

http://ec2-3-87-119-148.compute-1.amazonaws.com:8000/admin
