### ISSUE TITLE
[Frontend] Creating HomePage Layout.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#250]
***Description*:**
Creating and adding the homepage layout. which will be the landing page.

***Todo's*:**
- [x] Create HomePage Layout.
- [x] Divide it into 3 parts as header, content, footer.
- [x] Align the components such that whenever the forum and article parts are complete, they will fit well.

***Reviewer*:** @yavuuzsameet 

***Task Deadline*:** 30.10.2022 23:00
***Review Deadline*:** 31.10.2022 12:00

**Comment by Keremgunduz7** [comment]
All 3 tasks are implemented. Review gathered in the related [PR](https://github.com/bounswe/bounswe2022group5/pull/257). Thanks.
Closing the issue
