### ISSUE TITLE
[Mobile] Using Personal Information and Logout API services in the home page

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#260]
***Description*:**

We have implemented our API services together in [Mobile Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-3). Now, we need to use these services to create a working app. As for my side of this work, I should use [Personal Information endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Personal-Info-documentation) to check whether the user is logged in or not and use [Logout endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Logout-Documentation) to log out the user in the home page I've created before. 

***Todo's*:**
- [ ] An API service method should be created to use [Personal Information endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Personal-Info-documentation) in the mobile app. This method can return the logged in user.
- [ ] This service method should be used to check whether a user is logged in the home page, if so, get his/her personal info.
- [ ] [Logout endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Logout-Documentation) should be used to log out the logged in user. 

***Reviewer*:** @bbenginbestas  

***Task Deadline*:** 30.10.2022 23:59  
***Review Deadline*:** 31.10.2022 12:00

**Comment by palahb** [comment]
- An API service method `getPersonalInfo` in the `ApiService` class has been created to use [Personal Information endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Personal-Info-documentation) in the mobile app. This method returns the logged in user if he/she is logged in, if not, returns null.
- This service method has been used to check whether a user is logged in the home page, if so, get his/her personal info and show in the drawer.
- [Logout endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Logout-Documentation) has been used to log out the logged in user and navigate him/her to the Login page.
- User model has been updated according to the available API functionality. It only have `token`, `email` and `type` fields for now. Mock users have been deleted since we do not need them from now on. There are still mock posts, but user field has been deleted from them.
- Some commenting have been done.

**Notes:** 
- Home Page constructor now needs a `token` in its constructor. Since the login page directs users to the home page, we should pass the token info coming from the [Login endpoint](https://github.com/bounswe/bounswe2022group5/wiki/Login-API-Documentation) of our API in the Home page constructor.
- User profile page does not need any change in its constructor. It should be updated just to reflect changes implemented in the `User` model.

**After #269 is reviewed, this issue will be closed automatically.**
