### ISSUE TITLE
[Mobile] Editing Profile Page 

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#275]
***Description*:**

After the creation of endpoints, the profile page must be edited. Also, other widgets should be corrected.

***Todo's*:**
- [x] Profile page must be edited
- [x] Names should be corrected
- [x] Image path should be corrected

***Reviewer*:** @palahb 

***Task Deadline*:** 31.10.2022 18:00
***Review Deadline*:** 31.10.2022 23:59
