### ISSUE TITLE
Milestone 1 Executive Summary

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#284]
***Description*:**

An executive summary of the project will be written for [Milestone 1 Group Review](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Milestone_1/M1_Report_Group5.md#group-review). It will include subcategories. I will be responsible for Introduction and Description sections. @Keremgunduz7 will be responsible for URL of the Deployed Application, Current Functionality of the Project, Some Challenges We Met sections.

***Todo's*:**

- [x] Introduction section will be added.
- [x] Description section will be added.
- [x] URL of the Deployed Application section will be added.
- [x] Current Functionality of the Project section will be added.
- [x] Some Challenges We Met section will be added.

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 04.11.2022 20:00
***Review Deadline*:** 04.11.2022 22:00

**Comment by enginoguzhansenol** [comment]
After gathering the reports about the related sections with @Keremgunduz7, I uploaded the [Executive Summary](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Milestone_1/M1_Report_Group5.md#1-executive-summary) section. Need review from @mehmetemreakbulut.

**Comment by mehmetemreakbulut** [comment]
I reviewed executive summary. Well done!
No errors.
Closing the issue!
