### ISSUE TITLE
Milestone 1 Evaluation of the status of deliverables

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#285]
***Description*:**

An evaluation of the status of deliverables will be written for [Milestone 1 Group Review](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Milestone_1/M1_Report_Group5.md#group-review). Subcategories is listed below.

***Todo's*:**

- [x] Software Requirements Specification Evaluation
- [x] Software Design (UML) Evaluation
- [x] Scenarios and Mockups Evaluation
- [x] Project Plan Evaluation
- [x] RAM Evaluation
- [x] Individual Contribution Reports Evaluation
- [x] Group Review Evaluation

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 04.11.2022 23:00
***Review Deadline*:** 04.11.2022 23:30

**Comment by mehmetemreakbulut** [comment]
- Evaluation of tools is available in [Group Review](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Milestone_1/M1_Report_Group5.md)
- 'Software' was added as a deliverable
- Need Review @canberkboun9

**Comment by canberkboun9** [comment]
I corrected 2 typos and added columns to indicate titles. Other than that, it is correctly written.
Thanks!
