### ISSUE TITLE
[Frontend] Creating Profile Page for Registered Users

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#288]
***Description*:**

Profile Page is going to be created for users to see their information and their activity histories such as liked posts or articles. 

***Todo's*:**
*For Members*:
- [x] Display avatar.
- [x] Display username.
- [x] Implement activity history part.

*For Doctors*:
- [x] Display profile picture.
- [x] Display name.
- [x] Implement activity history part.

***Reviewer*:** @Oozankilic  

***Task Deadline*:** 05.12.2022 14:00
***Review Deadline*:** 05.12.2022 23:00

**Comment by yavuuzsameet** [comment]
Some commits are made. Please see the [pull request](https://github.com/bounswe/bounswe2022group5/pull/356). 
- Articles and Posts are retrieved from backend for display.
- Profile page is initialized, and some features such as activity history are implemented. 
- Different pages with similar purposes are made similar.

**Comment by Oozankilic** [comment]
Profile page seems eye-catching, thank you for good job! There is just a minor part that could be updated, under the e-mail address of the user at the profile page, a number is written instead of doctor or member, it might be more explanatory.

**Comment by yavuuzsameet** [comment]
All parts have been completed, and requests by @Oozankilic implemented. You can see the changes made in [this](https://github.com/bounswe/bounswe2022group5/pull/384) merge request.

**Comment by Oozankilic** [comment]
It seemed perfect to me, thank you for your collaborations. Issue can be closed after reviewers merge the branch
