### ISSUE TITLE
[Backend] Implementing Post CRUD operations and endpoints

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#290]
***Description*:**

Our application consists of posts and their threads with comments. So, as a first step Post Create, Read, Update and Delete operations must be implemented. 

***Todo's*:**
- [x] Get all posts endpoint.
- [x] Get post by id endpoint.
- [x] Create post endpoint.
- [x] Add pagination for 'get all posts endpoint'.

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 14.11.2022 22:00
***Review Deadline*:** 15.11.2022 12:00

**Comment by oguzhandemirelx** [comment]
I apologize for the delay. I forgot about this issue after merging the pull request. I appreciate your work. We can close this issue.
