### ISSUE TITLE
[Mobile] Updating models and creating new ones

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#295]
***Description*:**

Existing models should be updated, new fields should be added. Also, some new models should be created. Mock data for every model should be added.

Models and their fields should be created based on the tables specified in the [Backend Meeting 2 Notes](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.2) and [Backend Meeting 3 Notes](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.3).

***Todo's*:**
- [x] Updating User model
- [x] Creating a Member model
- [x] Creating a Doctor model
- [x] Updating Post model
- [x] Creating Comment model
- [x] Creating Article model

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 18/11/2022 23:59  
***Review Deadline*:** 19/11/2022 12:00

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR [#317](https://github.com/bounswe/bounswe2022group5/pull/317) for further explanations. After @kardelendemiral's review of the PR, this issue will be closed.
