### ISSUE TITLE
[Frontend] Adding categories to the sidebar

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#301]
***Description*:**

Every post has a category. At the post and article pages, there should be a section which includes all the categories. When a category on that section is selected, the posts/articles about the category should be shown. This section will be added to homepage.

***Todo's*:**
- [x] Creating category list
- [x] Connecting backend and frontend
- [x] Listing categories coming from backend

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 20.11.2022 22:00  
***Review Deadline*:** 21.11.2022 23:50

**Comment by Keremgunduz7** [comment]
I am not very sure that whether or not we can complete this task before the milestone since there is no categories or search related parts in the backend. Maybe we can stale this issue at least for now and focus on to other tasks.

**Comment by Oozankilic** [comment]
Yes, it looks like I'm a bit late to handle the issue. My bad, I could talk with backend team, sorry for delay. For this milestone, we can postpone it and I will implement it until final milestone.

**Comment by Oozankilic** [comment]
The branch is ready before milestone 2. It is merged to the main branch. Issue can be closed
