### ISSUE TITLE
[Frontend] Making improvements on the forum

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#302]
***Description*:**

Forum page needs some corrections and backend connection with frontend should be codded.

***Todo's*:**
- [x] Making like/dislike responsive
- [x] Fetching data from backend
- [x] Listing post coming from backend.

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 20.11.2022 22:00  
***Review Deadline*:** 21.11.2022 23:50

**Comment by Keremgunduz7** [comment]
@Oozankilic maybe we can speed up the process since the milestone is approaching soon.

**Comment by Oozankilic** [comment]
Thank you for reminder @Keremgunduz7 , I will finalize my works as soon as possible
