### ISSUE TITLE
[Backend] Implementing Article CRUD operations, endpoints and tests

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#303]
***Description*:**

Our application consists of articles So, as a first step Articles Create, Read, Update and Delete operations must be implemented. 
Also, I will try to write tests as much as possible.

***Todo's*:**
- [x] Get all articles endpoint.
- [x] Get article by id endpoint.
- [x] Create article endpoint.
- [x] Update article endpoint.
- [x] Delete article endpoint.
- [x] Add pagination for 'get all articles endpoint'.
- [x] Article unit tests

***Reviewer*:** @irfanbozkurt 

***Task Deadline*:** 21.11.2022 22:00
***Review Deadline*:** 22.11.2022 12:00

**Comment by mehmetemreakbulut** [comment]
* Implemented get all, get by id and create article endpoints. 
* Pagination is implemented and very similar to the APIs for posts.
* Exceptions were not implemented in an efficient way for post endpoints, so I added exceptions properly for article.

**Comment by mehmetemreakbulut** [comment]
* I added update and delete endpoints.
* Pagination implemented for "get all articles" endpoint.
* Unit tests were written.
* I also realized that swagger documentation would be beneficial for FE and Mobile teams. I will open an issue for this.

**Comment by mehmetemreakbulut** [comment]
[PR](https://github.com/bounswe/bounswe2022group5/pull/304) is open for this issue.
Need review! @oguzhandemirelx
