### ISSUE TITLE
[Backend] Integrate S3 bucket interaction

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#306]
***Description*:**

Static images can be pulled directly from a publicly-readable S3 bucket.

***Todo's*:**
- [x] Integrate AWS credentials as environment variables
- [x] Integrate boto3 library
- [x] Create a "common" module for S3 interaction
- [x] Implement upload_to_s3 and delete_from_s3

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 21.11.2022 22:00

**Comment by irfanbozkurt** [comment]
Review can continue on the PR
