### ISSUE TITLE
[Backend] Profile module & profile picture capability

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#308]
***Description*:**

Implement a profile module and put profile picture uploading capability as a reference for other object-uploading modules, like "images of a post"

***Todo's*:**
- [x] Create a new "user_profile" module
- [x] Create a new endpoint to upload a profile picture to S3
- [x] Create a new endpoint to delete a profile picture from S3

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 21.11.2022 22:00

**Comment by irfanbozkurt** [comment]
This issue now needs to be held back, because different user types must be handled before we can distinguish if a user is a doctor or a member.
At the end of the day, members won't be able to upload a pp, while doctors will.

**Comment by mehmetemreakbulut** [comment]
I have merged PR. We can close the issue now
