### ISSUE TITLE
[Backend] Upvote and Downvote enpoints for Articles

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#312]
***Description*:**

In our application, registered users are able to upvote and downvote an article. So we need to implement upvote and downvote endpoints for Articles. 

***Todo's*:**
- [x] Create a new endpoint to upvote an article
- [x] Create a new endpoint to downvote an article
- [x] Write tests for new endpoints

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 21.11.2022 22:00

**Comment by oguzhandemirelx** [comment]
Implemented two endpoints for upvoting and downvoting and also related tests.
Waiting the review from @mehmetemreakbulut, see the [PR](https://github.com/bounswe/bounswe2022group5/pull/314)

**Comment by mehmetemreakbulut** [comment]
I merged PR. We can close the issue
