### ISSUE TITLE
[Backend] Upvote and Downvote enpoints for Posts

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#313]
***Description*:**

In our application, registered users are able to upvote and downvote a post. So we need to implement upvote and downvote endpoints for Posts. 

***Todo's*:**
- [x] Create a new endpoint to upvote a post
- [x] Create a new endpoint to downvote a post
- [x] Write tests for new endpoints

***Reviewer*:** @irfanbozkurt   

***Task Deadline*:** 21.11.2022 22:00

**Comment by oguzhandemirelx** [comment]
Implemented two endpoints for upvoting and downvoting and also related tests.
Waiting the review from @irfanbozkurt , see the [PR](https://github.com/bounswe/bounswe2022group5/pull/321)

**Comment by irfanbozkurt** [comment]
LGTM! We tested the code together in a private meeting, and functionality seems like it's correct. Waiting for the PR.

**Comment by irfanbozkurt** [comment]
Reviewed and PR is merged.
