### ISSUE TITLE
[Mobile] Updating Profile Page

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#318]
***Description*:**

The created profile page will be updated for the mobile application.

***Todo's*:**

- [ ] Upvotes page of Activity History will be added.
- [ ] Comments page of Activity History will be added.
- [ ] Posts page of Activity History will be added.
- [ ] Edit profile page will be added.

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 18.11.2022 23:59
***Review Deadline*:** 19.11.2022 12:00
