### ISSUE TITLE
[Mobile] Creating Articles Home Page 

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#322]
***Description*:**

For the time being, there is no Articles section in our mobile home page. There should be a page in which all created articles can be seen and can be reached.

***Todo's*:**
- [x] Article item that will be shown for every article in the home page should be created.
- [x] A list of article items should be shown in the home page.
- [x] This Articles section should be reached via bottom navigation bar.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 27.11.2022 12:00  
***Review Deadline*:** 27.11.2022 23:59

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR [325](https://github.com/bounswe/bounswe2022group5/pull/325) for further explanations. After @enginoguzhansenol's review of the PR, this issue will be closed.
