### ISSUE TITLE
[Backend] Voting feature improvements. 

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#329]
***Description*:**

We can upvote and downvote posts, comments, and articles in our application, but we don't look at the user's prior upvotes or downvotes. In order to check upvotes and downvotes, we will add fields to the user object. Then, we will update the upvote and downvote endpoints as needed.

***Todo's*:**
- [x] Add necessary fields to User object.
- [x] Revise upvote and downvote endpoints.
- [x] Revise tests for these endpoints.

***Reviewer*:** @irfanbozkurt   

***Task Deadline*:** 29.11.2022 22:00

**Comment by oguzhandemirelx** [comment]
User object, upvote, downvote endpoints and tests updated.

**Comment by irfanbozkurt** [comment]
Reviewed and the PR is merged.
