### ISSUE TITLE
[Backend] Fixes on Post and Article Endpoint

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#338]
***Description*:**

Fundamental structure of APIs is built, however, we have to add new fields or configs to align with frontend and mobile. Some fixes we determined listed below.

***Todo's*:**
- [x] Add location to Post
- [x] Fix pagination in 'user's post' and 'user's articles' endoint.
- [x] Add image upload to posts and articles.
- [ ] Test with FE team and Mobile Team
- [x] Comment CRUD Operations

***Reviewer*:** @oguzhandemirelx    

***Task Deadline*:** 28.11.2022 22:00

**Comment by mehmetemreakbulut** [comment]
* Also comment CRUD operations are missing. Added it to Todo's.

**Comment by mehmetemreakbulut** [comment]
- Added voting info('upvote', 'downvote', null) to post and its comments in get_post endpoint.
