### ISSUE TITLE
[Mobile] Connecting post and article reading/creation pages to the home page

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#342]
***Description*:**

Necessary page connections should be implemented between home page and article/post reading/creation pages.

***Todo's*:**
- [x] Article reading page should be connected to the home page (via separate article item widgets).
- [x] Post reading page should be connected to the home page (via separate post item widgets).
    - [x] Comment creation should be specific to logged in users.
- [x] Article creation page should be connected to the home page (via floating action button).
- [x] Post creation page should be connected to the home page (via floating action button).

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 03.12.2022 12:00  
***Review Deadline*:** 03.12.2022 23:59

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/380 for further explanations. After @kardelendemiral's review of the PR, this issue will be closed.
