### ISSUE TITLE
[Backend] Get a doctor's all articles

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#353]
***Description*:**

We need all articles for a doctor to show on his/her profile page. So we have to implement a get endpoint to fetch all articles for a doctor. Also we have to add new fields for get article method.

***Todo's*:**
- [x] Add get article for a doctor endpoint.
- [x] Add new fields to get article endpoint.
- [x] Add new fields and endpoints to documentation. 

***Reviewer*:** @irfanbozkurt   

***Task Deadline*:** 02.12.2022 22:00

**Comment by canberkboun9** [comment]
I left a review under the PR

**Comment by canberkboun9** [comment]
Thanks Oğuzhan! PR is merged, we can close the issue for now
