### ISSUE TITLE
[Mobile] Upvote/Downvote functionalities should be implemented

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#359]
***Description*:**

Upvote and Downvote functionalities for articles, posts and comments should be implemented.

***Todo's*:**
- [ ] API function for post upvote should be implemented.
- [ ] API function for post downvote should be implemented.
- [ ] API function for article upvote should be implemented.
- [ ] API function for article downvote should be implemented.
- [ ] API function for comment upvote should be implemented.
- [ ] API function for comment downvote should be implemented.
- [ ] Necessary page connections for upvote/downvote should be made.

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 04.12.2022 12:00
***Review Deadline*:** 04.12.2022 23:59

**Comment by kardelendemiral** [comment]
[Related PR](https://github.com/bounswe/bounswe2022group5/pull/415) is merged. I am closing the issue.
