### ISSUE TITLE
[Mobile] Post/Comment/Article deletion functionalities should be implemented

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#360]
***Description*:**

Deletion functionalies  for Post, Comment and Article should be implemented

***Todo's*:**
- [x] Post delete API function should be implemented.
- [ ] Comment delete API function should be implemented.
- [x] Article delete API function should be implemented.
- [x] Necessary page connections should be made.

***Reviewer*:** @bbenginbestas  

***Task Deadline*:** 04.12.2022 12:00 
***Review Deadline*:** 04.12.2022 23:59

**Comment by kardelendemiral** [comment]
We decided to implement comment deletion later. So, comment deletion will be added with another PR later on. The other necessary functionalities are implemented with the PR #419 and it is merged. So, we can close this issue. We'll open another issue for comment deletion later.
