### ISSUE TITLE
[Frontend] Implementing Create Post Page.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#362]
***Description*:**

Create Post page will be implemented. It should satisfy the requirements as adding image, geolocation, title, body.

***Todo's*:**
- [x] Initial version of the post creation page will be implemented.
- [x] Adding image integration into the posts and fetching current geolocation from the client and sending to the database.
- [x] Necessary backend endpoints will be used for posting the "Post" to the database.

***Reviewer*:** @burakmert236 

***Task Deadline*:** 4.12.2022 22:00  
***Review Deadline*:** 5.12.2022 12:00

**Comment by Keremgunduz7** [comment]
Implemented the tasks and opened the related PR connected with this issue. Could you please check it?
