### ISSUE TITLE
[Frontend] Adding buttons in the Homepage and Navbar

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#363]
***Description*:**

Necessary buttons and the functionalities in the HomePage and Navigation Bar will be implemented.

***Todo's*:**
- [x] Create Post, Create Article buttons will be added to the HomePage.
- [x] Profile Page button will be added to the Navigation Bar.
- [x] Functionalities of these buttons will be implemented

***Reviewer*:** @yavuuzsameet  

***Task Deadline*:** 04.12.2022 22:00  
***Review Deadline*:** 05.12.2022 12:00

**Comment by Keremgunduz7** [comment]
Added logo, profile page buttons on the navigation bar. Also added create post and article buttons on the homepage and connected to the pages that is creation going to be done.

**Comment by yavuuzsameet** [comment]
Functionalities will be useful, thanks for the work. I am now checking merge request.
