### ISSUE TITLE
[Frontend] Implementing Create Article Page.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#365]
***Description*:**

Create Article page will be implemented. It should satisfy the requirements as adding image, geolocation, title, body.

***Todo's*:**
- [x] Initial version of the article creation page will be implemented.
- [x] Adding image integration into the posts and sending to the database.
- [x] Necessary backend endpoints will be used for posting the "Article" to the database.

***Reviewer*:** @burakmert236 

***Task Deadline*:** 4.12.2022 22:00  
***Review Deadline*:** 5.12.2022 12:00

**Comment by Keremgunduz7** [comment]
Created The page, it is very similar to the Post Creation page at this moment. Could you please review the related PR and any suggestions are welcomed in terms of the design.
