### ISSUE TITLE
[Backend] Response formatting for Profile, Post and Articles

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#366]
***Description*:**

Some fields are demanded from frontend and mobile team for endpoints in profile module. Also for post and articles we need `id` in responses. Also location field will not be required.

***Todo's*:**
- [ ] Profile Endpoints refactoring
- [ ] Adding missing fields to Post and Articles
- [ ] Location field is optional.
- [ ] Search Query
- [ ] Updating Documentation

***Reviewer*:** @oguzhandemirelx  

***Task Deadline*:** 03.12.2022 18:00  
***Review Deadline*:** 03.12.2022 23:59

**Comment by mehmetemreakbulut** [comment]
* I have implemented the tasks above and MR is reviewed.
* Search query will be added by last commit in the same branch.

**Comment by mehmetemreakbulut** [comment]
* Search functionality is implemented in forum page. You can use it with `q` parameter in query.
