### ISSUE TITLE
[Mobile] Updating edit profile page

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#376]
***Description*:**

The created edit profile page will be updated with new enhancements.

***Todo's*:**

- [ ] Changing avatar will be completed for members.
- [ ] Different forms for different user types will be added.
- [ ] Necessary form fields should be added to the edit profile page.
- [ ] API connections for edit profile will be created.

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 04.12.2022 12:00
***Review Deadline*:** 04.12.2022 23:59
