### ISSUE TITLE
[Backend] Label and Category added to Posts and Articles

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#383]
***Description*:**
Articles and Posts will ve created with Category and labels derived from ontology. So we need to get them when creating article or post. Also, these fields must be added to serializer.

***Todo's*:**
- [x] Category added to Post
- [x] Category added to Article
- [x] Label added to Post
- [x] Label added to Post

***Reviewer*:** @oguzhandemirelx  

***Task Deadline*:** 04.12.2022 18:00  
***Review Deadline*:** 04.12.2022 23:59

**Comment by mehmetemreakbulut** [comment]
* I have implemented Category and Label fields for post. When creating post and articles, it will given with payload. 
* Also I will implement the search functionalities with Category and Label.

**Comment by mehmetemreakbulut** [comment]
* I have implemented fundamental functionalities and endpoint of category and label. For labels we use ontology of Natinal Library of Medicine [Medical Subject Headings(MeSH)](https://www.nlm.nih.gov/mesh/meshhome.html). 
* We are accepting every label from users and linking these labels with the ontology mentioned above. We will implement suggestion labels by using MeSH as next feature.

**Comment by oguzhandemirelx** [comment]
I reviewed and merged the related PR. Thanks for your effort.
