### ISSUE TITLE
[Mobile] 'ViewPost' page Bug Fixes

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#386]
***Description*:**

Some bugs have occured in view post page. These bugs will be fixed.

***Todo's*:**
- [x] Solving overflow bug in smaller mobile screens.
- [x] Deleting 'Report' buttons from comments and posts.
- [x] Constructor requires 'activeUser'.

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 05.12.2022 13:00  
***Review Deadline*:** 05.12.2022 23:59
