### ISSUE TITLE
[Mobile] Adding dropdown for 'ViewArticle' page

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#388]
***Description*:**

Dropdowns will be added to the article in the 'ViewArticle' page.

***Todo's*:**
- [x] Dropdown icon will be added at the top-right of the article.
- [x] The dropdown will include 'Edit' and 'Delete' if it was created by the active user.
- [x] The dropdown will have 'Report' if it was not created by the active user.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 05.12.2022 13:00  
***Review Deadline*:** 05.12.2022 23:59

**Comment by bbenginbestas** [comment]
PR merged by my teammate. Closing the issue.
