### ISSUE TITLE
[Mobile] Article/Post adding categories and labels

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#393]
***Description*:**

Categories and labels of posts and articles also should be sent with API calls.

***Todo's*:**
- [x] API function for create post will be updated.
- [x] API function for create article will be updated.
- [x] Necessary page connections will be made.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 05.12.2022 12:00  
***Review Deadline*:** 05.12.2022 17:00

**Comment by kardelendemiral** [comment]
See [the PR #395](https://github.com/bounswe/bounswe2022group5/pull/395). Needs review.
