### ISSUE TITLE
[Mobile] Activity History Pages

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#399]
***Description*:**

Activity history pages will be completed for all user types.

***Todo's*:**

- [ ] Activity history of shared articles for doctors is added .
- [ ] Activity history of shared posts for all users is added .
- [ ] Activity history of upvotes for all users is added .
- [ ] Activity history of made comments for all users is added .

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 05.12.2022 18:00
***Review Deadline*:** 05.12.2022 23:59
