### ISSUE TITLE
[Mobile] Getting a Specific Post and Article from Backend

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#402]
***Description*:**

Now, we can get all posts and articles in the home page. From now on, we need to get a single post and article from the backend when we touch a single post/article. Some changes in the post/article pages may be needed.

***Todo's*:**
- [x] API function for getting single post
- [x] API function for getting single article
- [x] Conecting these functions to related mobile pages
- [x] Necessary changes in the post/article reading pages

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 05.12.2022 21:00
***Review Deadline*:** 05.12.2022 23:59

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/408 for further explanations. After @enginoguzhansenol's review of the PR, this issue will be closed.
