### ISSUE TITLE
[Frontend] Navigation handling of buttons

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#404]
***Description*:**

- Some minor errors are fixed, mainly on profile but also some other files.

***Tasks Done*:**
- [x] Navigations of the log-out and logo buttons are handled.
- [x] FetchMe was not working, it is dispatched.
- [x] Notification errors on the profile page are handled.
- [x] API calls are fixed.

***Reviewer*:** @burakmert236  

***Task Deadline*:** 05.12.2022 18:00
***Review Deadline*:** 05.12.2022 23:00
