### ISSUE TITLE
[Frontend] Adding category section to the create post page

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#406]
***Description*:**

- Category button will be added to the create post page, and its functionality will be implemented.

***Tasks Done*:**
- [x] Display category dropdown at the create post page.
- [x] Fetch categories from backend.
- [x] Send category information while creating a post.

***Reviewer*:** @Keremgunduz7   

***Task Deadline*:** 05.12.2022 18:00
***Review Deadline*:** 05.12.2022 23:00

**Comment by yavuuzsameet** [comment]
In addition to that, I have handled the post and article cards. The cards are now redirecting to their specific pages.
