### ISSUE TITLE
[Mobile] Updating Pages After Comment/Article/Post Creations

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#411]
***Description*:**

We need to update pages to show updated versions of them after Comment/Article/Post creations.

***Todo's*:**
- [x] Update forum page after post creation.
- [x] Update articles page after article creation.
- [x] Update post page after comment creation

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 05.12.2022 22:00
***Review Deadline*:** 05.12.2022 23:59

**Comment by palahb** [comment]
Updating forum and articles page has been done by @kardelendemiral in #419. Update after new comment has been done by me. More info can be found in #420. This issue will be closed after @kardelendemiral's review of the PR #420.
