### ISSUE TITLE
[Mobile] Show HTML Body Of a Post/Article

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#412]
***Description*:**

We need to render HTML while showing Post/Articles.

***Todo's*:**
- [x] Show HTML body in Post Viewing Page
- [x] Show HTML body in Article Viewing Page
- [x] Show HTML bodies in Forum Page

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 05.12.2022 22:00
***Review Deadline*:** 05.12.2022 23:59

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/418 for further explanations. After @kardelendemiral's review of the PR, this issue will be closed.
