### ISSUE TITLE
[Mobile] Showing images of Post/Article/Comment

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#421]
***Description*:**

We need to show images of a post/article/comment.

***Todo's*:**
- [x] Showing images of a post in post page
- [x] Showing images of an article in article page
- [x] Showing images of a comment in post page

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 06.12.2022 12:00
***Review Deadline*:** 06.12.2022 14:00

**Comment by palahb** [comment]
Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/425 for further explanations. After @enginoguzhansenol's review of the PR, this issue will be closed.
