### ISSUE TITLE
[Frontend] Improvements on the profile page

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#423]
***Description*:**

Profile Page will be improved, user info editing and display will be variated and medical history for members are going to be implemented.

***Todo's*:**
*For Members*:
- [x] Display Medical History.
- [x] Add fields to the editing info section.

*For Doctors*:
- [x] Add fields to the display info section.

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 06.12.2022 09:00
***Review Deadline*:** 06.12.2022 12:00
