### ISSUE TITLE
[Milestone Presentation] Adding mobile screens to Scenarios

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#429]
***Description*:**
For milestone 2, as a member of the mobile team, I will add screenshots of necessary screens to Scenarios.

***Todo's*:**

- [x] Adding screenshots to Scenario 1
- [x] Adding screenshots to Scenario 2
- [x] Adding screenshots to Scenario 3

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 09.12.2022 17:00
***Review Deadline*:** 09.12.2022 17:00

**Comment by canberkboun9** [comment]
- Thanks for the effort! 
- It looks correct. 
- Closing the issue
