### ISSUE TITLE
[Backend] Category Follow Implementation

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#431]
***Description*:**

Registered users should follow some categories in website to take recommended posts and articles. So we need to implement category follow function.

***Todo's*:**
- [x] New endpoint for category follow.
- [x] Add unit tests for that endpoint.
- [x] Change necessary fields on User. 

***Reviewer*:** @irfanbozkurt   

***Task Deadline*:** 17.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
* New endpoint /profile/follow_category/categoryId added.
* Unit tests for that endpoint added.
* followed_categories field added on CustomUser
