### ISSUE TITLE
[Backend] Refactoring After Milestone 2

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#434]
***Description*:**

For Milestone 2 we have implemented general functionalities of the application. However, there is still missing part in backend in in term of convention. Also, I will make the codebase more clear and understandable.

***Todo's*:**
- [x] Refactoring of Endpoints
- [x] Refactoring of Models
- [x] Refactoring of Serializers

***Reviewer*:** @canberkboun9    

***Task Deadline*:** 16.12.2022 24:00

**Comment by mehmetemreakbulut** [comment]
- I have reviewed the code and found some parts that needed to refactor in Forum and Articles module
- Not functional changes but need refactoring of course!

**Comment by mehmetemreakbulut** [comment]
- Forum and Articles endpoints refactored.
- I have opened PR. 
- Need review @canberkboun9 !

**Comment by canberkboun9** [comment]
I reviewed and merged the PR. We can close the issue now. Nice work!
