### ISSUE TITLE
[Backend] Annotation Backend

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#436]
***Description*:**

- As we show in [Annotation Mockup](https://github.com/bounswe/bounswe2022group5/wiki/Annotation-Mockup), annotation will be implemented with text and image annotation functionalities. 
- An annotation database and APIs are needed for this. I will follow the rules in this [link](https://devopedia.org/web-annotation#qst-ans-1) as guide when implementing annotation. 
- For now I will implement Text annotation.

***Todo's*:**
- [x] Annotation Models to store in DB
- [x] Create Text Annotation endpoint 
- [x] Get Text Annotation endpoint

***Reviewer*:** @oguzhandemirelx    

***Task Deadline*:** 17.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
Annotations work properly, well done. Closing the issue.
