### ISSUE TITLE
[Frontend] Adding editing medical history feature

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#438]
***Description*:**

- The medical histories of users will be editable, and users will be able to add new illnesses, drugs, allergies, operations, and diseases to their medical history.

***To Do*:**
- [x] Change the z-index of the popup component so that it will come out on top.
- [x] Implement editing functionality for medical history.
- [x] Display the medical history on the profile page.

***Reviewer*:** @burakmert236     

***Task Deadline*:** 18.12.2022 22:00
***Review Deadline*:** 18.12.2022 23:00
