### ISSUE TITLE
[Backend] Geospatial search

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#440]
***Description*:**

Our posts have "longitude" and "latitude" information.
Can we find a way to make the PSQL database calculate distances? If so, then we can easily implement **geospatial search**.

***Todo's*:**
- [x] Have overall research on PSQL geospatial search
- [x] Pick one of the suitable ways
- [x] Implement a PSQL query to return posts created within a given distance

***Task Deadline*:** 17.12.2022 22:00

**Comment by irfanbozkurt** [comment]
2 of the suitable ways are:
1. Install PSQL plugins cube and earthdistance, and support for distance-based queries become native
2. Just use the [Spherical Law of Cosines in a query](https://en.wikipedia.org/wiki/Spherical_law_of_cosines)

I'll go with the second one because this solution is easier to implement, doesn't require a re-indexing of the database, and the precision is good enough.

**Comment by irfanbozkurt** [comment]
I've written the corresponding PSQL query:

![Screen Shot 2022-12-17 at 16 57 57](https://user-images.githubusercontent.com/38441731/208245519-4a3893e0-3a24-4ab6-89eb-1777ca8398c7.png)

This query returns distance between TARGET and SOURCE in kilometers, and I've verified the results using [NATIONAL OCEANIC AND ATMOSPHERIC ADMINISTRATION](https://www.nhc.noaa.gov/gccalc.shtml)'s website.

Error rate is <1%, so we're good to go.

**Comment by irfanbozkurt** [comment]
Now that we have the query, I'm closing this issue and creating another issue for the implementation.
Cheers!!
