### ISSUE TITLE
[Frontend] Following and Unfollowing Categories

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#448]
***Description*:**

- The categories on the sidebar are going to be followable and unfollowable by the registered users. Guest users will not be able to see the follow or unfollow buttons until they are signed up to the system.

***To Do*:**
- [x] Implement follow and unfollow buttons.
- [x] Retrieve category information from the backend.
- [x] Send the input to the backend to store the necessary information about a category being followed by a user or not.

***Reviewer*:** @Keremgunduz7      

***Task Deadline*:** 18.12.2022 22:00
***Review Deadline*:** 18.12.2022 23:00
