### ISSUE TITLE
[Frontend] Visualizing added labels

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#451]
***Description*:**

- In milestone 2, I have implemented the label adding functionality to the posts. Hoever, they were not visualized as the user created the labels.
- The labels which are added to the posts need to be visualized in the create post page as the user inputs the label.

***To Do*:**
- [x] Display the labels on the create post page after the user initializes.
- [x] Add functionality to labels such that they will be removed from labels as they are clicked.
- [x] Output notification messages.

***Reviewer*:** @Oozankilic       

***Task Deadline*:** 18.12.2022 22:00
***Review Deadline*:** 18.12.2022 23:00

**Comment by Oozankilic** [comment]
The checklist is completed. Thank you for great efforts, after code review the issue can be closed.
