### ISSUE TITLE
[Backend] Annotation Data Model

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#453]
***Description*:**
We started to implement annotation and an API is needed to handle the annotation schema that comes from Frontend. For Posts and Articles we have to store Annotations. Create, Update, Delete and Get functionalities  of Annotation will be imlemented.
W3 Annotation Data Model followed. 

***Todo's*:**
- [x] Annotation Create and Get Methods
- [x] Annotation Update and Delete Methods
- [x] Annotation Schema mapper 
 
***Reviewer*:** @canberkboun9    

***Task Deadline*:** 18.12.2022 22:00

**Comment by mehmetemreakbulut** [comment]
- I have implement Schema mapper.
- CRUD Operatins are done
- Documentation updated
- See PR I will open for schema and example request.

**Comment by mehmetemreakbulut** [comment]
- PR is open #454 
- Need review @irfanbozkurt

**Comment by canberkboun9** [comment]
İrfan reviewed and merged the PR long ago. Review of the issue handed over to me to close the issue.
