### ISSUE TITLE
[Frontend] Initialization of Annotation Creation

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#455]
***Description*:**

Appropriate react libraries will be found to implement text and image annotations. Annotation creation will implemented for discussion thread page and article display page without backend API connections.

***Todo's*:**
- [x] Appropriate react libraries will be found for image and text annotations.
- [x] Initial structure of annotation creation for discussion thread page.
- [x] Initial structure of annotation creation for article display page.

***Reviewer*:** @Oozankilic 

***Task Deadline*:** 20.11.2022 23:59
***Review Deadline*:** 20.12.2022 12:00

**Comment by burakmert236** [comment]
I found [@recogito/recogito-js](https://www.npmjs.com/package/@recogito/recogito-js) library for text annotation and [@recogito/annotorious](https://www.npmjs.com/package/@recogito/annotorious) library for image annotation. I built initial structure to use these tools and pushed them to the [this branch](https://github.com/bounswe/bounswe2022group5/tree/frontend/feature/annotation-creation-init-%23455).

**Comment by Oozankilic** [comment]
It seems pretty good to me. Thank you for your great contributions, issue can be closed.
