### ISSUE TITLE
[Mobile] Search Functionality Implementation

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#458]
***Description*:**

Search functionality for mobile application should be implemented.

***Todo's*:**
- [x] Post search by category will be implemented with necessary pages and API connections.
- [x] Post search by keyword will be implemented with necessary pages and API connections.
- [x] Post search by geolocation will be implemented with necessary pages and API connections.
- [x] Post search by username/doctor name will be implemented with necessary pages and API connections.
- [x] Article search by category will be implemented with necessary pages and API connections.
- [x] Article search by keyword will be implemented with necessary pages and API connections.
- [x] Article search by doctor name will be implemented with necessary pages and API connections.

***Reviewer*:** @palahb 

***Task Deadline*:** 25.12.2022 23:00  
***Review Deadline*:** 26.12.2022 12:00

**Comment by kardelendemiral** [comment]
All the necessary search functionalities are implemented. Post search by username/doctor name and article search by doctor name are decided to be done in the keyword search section by the backend team. So separate pages were not created. 
See: [related PR](https://github.com/bounswe/bounswe2022group5/pull/487). It needs review.

**Comment by palahb** [comment]
PR is reviewed. Issue can be closed.
