### ISSUE TITLE
[Mobile] Implementing text annotations

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#459]
***Description*:**

Text annotation functionality should be added to the mobile app.

***Todo's*:**
- [x] Creating a page for text annotation creation
- [x] Creating a text annotation data model
- [x] Creating an API function for text annotation creation
    - [x] API function for annotation creation
    - [x] API function for getting previously created annotations of a post/article
- [x] Implementing necessary changes in the post and article reading pages:
    - [x] Adding textselection functionality to the post and article pages, adding annotation creation option
    - [x] Adding a section for seeing previously created annotations
 - [x] Creating a page for seeing previously created annotations

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 25.12.2022 23:59  
***Review Deadline*:** 26.12.2022 23:59

**Comment by palahb** [comment]
- #454 can be helpful while creating an annotation data model.

**Comment by palahb** [comment]
- Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/502 for further explanations and screenshots of the text annotation feature. After @enginoguzhansenol's review of the PR, this issue will be closed.
