### ISSUE TITLE
[Backend] Bookmark a Post implementation

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#462]
***Description*:*
We received feedback regarding bookmarking posts and articles in customer milestone 2. A registered user may save a post or article and return to it at any time. So I'll put the following into action.

***Todo's*:**
- [x] New endpoint for bookmark a post.
- [x] New endpoint for getting all bookmarked posts.
- [x] Add unit tests for that endpoints.
- [x] Change necessary fields on User. 

***Reviewer*:** @mehmetemreakbulut    

***Task Deadline*:** 23.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
New two endpoints added, unit tests added. Get all posts and get post of a user endpoints changed due to bookmark improvements.

**Comment by canberkboun9** [comment]
Merged the PR. Closing the issue.
