### ISSUE TITLE
[Frontend] Creating Doctor Profile Pages

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#464]
***Description*:**

- The profile pages of users are implemented earlier. However, the profile of the user is only reachable to that user. 
- The doctor profiles need to be reachable to everyone.
- The member profiles will be kept as it is for keeping the privacy of the member.

***To Do*:**
- [x] Create doctor profile pages.
- [x] Make necessary connections to the backend.
- [x] Make doctor names in the platform clickable, which navigates to that doctor's profile on click.
- [x] Display doctor info on the profile page.
- [x] Disable editing on these pages.

***Reviewer*:** @burakmert236        

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00
