### ISSUE TITLE
[Mobile] Chatbot Implementation

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#465]
***Description*:**

A chatbot where users learn about possible diseases by selecting the aching parts of their body and also by telling their symptoms will be created for mobile application. The chatbot conversation will be taken from [the created page](https://github.com/bounswe/bounswe2022group5/wiki/Chatbot-Conversation-Tree). Mobile ver

***Todo's*:**

- [x] The initial page will be created.
- [x] Conversation models will be created.
- [ ] Redirections from categories will be added.

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 25.12.2022 12:00
***Review Deadline*:** 25.12.2022 15:00

**Comment by enginoguzhansenol** [comment]
After some research, we had decided to implement the chatbot using [kommunicate.io](https://www.kommunicate.io). We have created the conversation models. See issue #489. Redirections for related pages should be added.
