### ISSUE TITLE
[Frontend] Implementing Chatbot on a modal.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#466]
***Description*:**

- Implementation of the chatbot is required for the project.
- Need to design and implement the functionality on the frontend

***To Do*:**
- [x] Design a simple chat modal for the ChatBot.
- [x] Fetch ChatBot conversations and trees from backend.
- [x] Create paths (by adding buttons) and implement their functionalities.
- [x] Make and implement necessary redirections and functions.

***Reviewer*:** @yavuuzsameet       

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00

**Comment by Keremgunduz7** [comment]
Used [Kommunicate.io](https://docs.kommunicate.io/docs/web-installation.html) together with mobile team to have a common chatbot. Therefore, there is no longer need to design a modal. Our defined tree should be added to the configurations of the bot on the Kommunicate Panel. Together, @Oozankilic , @enginoguzhansenol and I going to add the nodes of the tree.

**Comment by Keremgunduz7** [comment]
That bot integrated with our application and PR is opened.
