### ISSUE TITLE
[Backend] Bookmark an Article

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#471]
***Description*:**
We received feedback regarding bookmarking posts and articles in customer milestone 2. A registered user may save a post or article and return to it at any time. So I'll put the following into action.

***Todo's*:**
- [x] New endpoint for bookmark an article.
- [x] New endpoint for getting all bookmarked articles.
- [x] Add unit tests for that endpoints.
- [x] Change necessary fields on User. 

***Reviewer*:** @mehmetemreakbulut    

***Task Deadline*:** 24.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
All todo's are done, also i added bookmark field on get all articles and get articles of a doctor endpoints.

**Comment by oguzhandemirelx** [comment]
PR merged, closing the issue.
