### ISSUE TITLE
[Documentation] Requirements editing for Final Milestone

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#479]
***Description*:**

Task 11 in [Meeting 24.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-24.1)

- [Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements) of our app needs some editing before Final Milestone as; we implemented some of them with different approach, some of the requirements became unnecessary, some will not be implemented due to the deadline and complexity. Also, we need new requirements, for example, for Annotation.
- We will give reasons for edited requirements.

***Todo's*:**
- [x] Requirements editing
- [x] Reasons for such editing
- [x] New requirements will be added
- [x] [Documentation in wiki](https://github.com/bounswe/bounswe2022group5/wiki/Changes-in-Requirements)

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 25.12.2022 20:00
***Review Deadline*:** 25.12.2022 22:00

**Comment by canberkboun9** [comment]
- Some requirements were modified.
- Some requirements were added.
- And some were deleted.
- Reasons for the actions were documented.

**Comment by canberkboun9** [comment]
- [Changes in Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Changes-in-Requirements) can be found here and on the Sidebar.
- Review is needed.

**Comment by oguzhandemirelx** [comment]
It seems okey to me. Thanks for your contribution.
