### ISSUE TITLE
[Frontend] Attaching Ontology suggested labels to the post pages

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#483]
***Description*:**

- The users are able to add labels to the posts, and the labels are visible to them.
- There is no current suggestion mechanism implemented yet. However, the backend team suggested that there will be related labels suggestion with the usage of the ontology database.
- These related labels will be placed on the post pages and they will redirect the users to the homepage, which contains posts and articles searched with that label.

***To Do*:**
- [x] Retrieve the labels of the post and related labels from the backend.
- [x]  Display labels and related labels in different sections.
- [x] Make them navigatable as described above.

***Reviewer*:** @Keremgunduz7        

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00

**Comment by yavuuzsameet** [comment]
On the demand of the team, the navigation of clicked labels will be onto a related Wikipedia page, not our search engine.
