### ISSUE TITLE
[Backend] Semantic Search using Ontology of National Library of Medicine

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#484]
***Description*:**
- So far our users have added some tags to posts and didn't use them effectively. Now, we are connecting these tags to ontology of [National Library of Medicine Medical Subject Headings](https://www.nlm.nih.gov/mesh/meshhome.html).
- User can see related tags of posts. These tags come from our semantic search engine, no user added them to posts. Via this labels user can go the related wikipage link of the tag.
- MeSH provides us to broader and narrower scopes of a given label.  I will write a sparql query to fetch related subject from ontology database. 

***To Do*:**
- [x] Semantic Search Engine initial creation
- [x]  Label search via Sparql query
- [x] Linking tags and giving them to user in response data of post

***Reviewer*:** @oguzhandemirelx    

***Task Deadline*:** 25.12.2022 18:00
***Review Deadline*:** 25.12.2022 22:00

**Comment by mehmetemreakbulut** [comment]
PR is merged and reviewed by @oguzhandemirelx . Closing issue.
