### ISSUE TITLE
[Mobile] Updating Medical History

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#490]
***Description*:**
The personal info in the profile page is not sufficient for mobile application. The medical history information for a user will be added to the profile pages.

***Todo's*:**
- [ ] Creating medical history page.
- [ ] Building the API connections for getting medical history.
- [ ] Building the API connections for updating medical history.
- [ ] Rearranging the profile page for new changes to avoid possible overflows

***Reviewer*:** @kardelendemiral     

***Task Deadline*:** 26.12.2022 17:00
***Task Deadline*:** 26.12.2022 22:00

**Comment by enginoguzhansenol** [comment]
Due to last changes, the descripted feature for medical history cannot be implemented to mobile application before the final milestone. The issue can be closed. Thanks for all the collaborations.
