### ISSUE TITLE
[Mobile] Redirecting to Doctor's Profile Page

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#491]
***Description*:**
A user can go to doctors' profile page to see their personal information by clicking their names while viewing a post or an article. Previosly, a user could only see own profile pages. Now, the doctor profile pages should be visible for everyone without editing and activity history. Thus, we need to create new screens for viewing doctor's profile.

***Todo's*:**
- [ ] Creating doctors' profile page for other users.
- [ ] Building the API connections for viewing doctors' profile page.
- [ ] Creating connections from posts and articles to created pages.

***Reviewer*:** @palahb      

***Task Deadline*:** 26.12.2022 17:00
***Task Deadline*:** 26.12.2022 22:00

**Comment by enginoguzhansenol** [comment]
I created the doctor profile page and made the API calls and redirections needed. After the related pull request merged, the issue will be closed automatically.
