### ISSUE TITLE
[Frontend] Delete Post implementation

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#493]
***Description*:**

- Implementation of the delete post functionality.

***To Do*:**
- [ ] Add Delete button on post page.
- [ ] Connect the button to deletion functionality.
- [ ] Connect backend post delete endpoint
- [ ] Make it only visible for post owners

***Reviewer*:** @burakmert236       

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00
