### ISSUE TITLE
[Frontend] Delete account feature

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#499]
***Description*:**

- The users were not able to delete their accounts. The account deletion functionality is going to be implemented.
- The users will be redirected to homepage in a logged out status, with their all information are deleted.

***To Do*:**
- [x] Add the Delete button on the profile page.
- [x] Connect the button to deletion functionality.
- [x] Connect backend account delete endpoint.
- [x] Make it only visible to the profile owner.

***Reviewer*:** @Oozankilic        

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00

**Comment by Oozankilic** [comment]
All the tasks are done, thank you for your efforts @yavuuzsameet, the issue will be closed automatically after the branch is merged to the master.
