### ISSUE TITLE
[Frontend] Article deletion feature

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#501]
***Description*:**

- The articles were not deletable previously. The article deletion functionality is going to be implemented.
- The articles can be deleted by only the article owner, and the system redirects the user to the homepage after deletion.

***To Do*:**
- [x] Add the Delete button on the article page.
- [x] Connect the button to deletion functionality.
- [x] Connect the backend article delete endpoint.
- [x] Make it only visible to the article owner.

***Reviewer*:** @burakmert236         

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00
