### ISSUE TITLE
[Mobile] Category following functionality

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#509]
***Description*:**

- Categories section has been added to the drawer in #506. Now, category following functionality should be implemented. Necessary API functions should be created and screen components created by @bbenginbestas should be improved.

***Todo's*:**
- [x] API function for getting all categories and followed categories by a user
- [x] API function for following/unfollowing categories
- [x] Category screen should be redesigned

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 26.12.2022 23:59  
***Review Deadline*:** 27.12.2022 01:00

**Comment by palahb** [comment]
- Necessary actions have been taken. Please see the PR https://github.com/bounswe/bounswe2022group5/pull/517 for further explanations. After @enginoguzhansenol's review of the PR, this issue will be closed.
