### ISSUE TITLE
[Final Milestone] User Manual

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#539]
***Description*:**

**Part a.** in the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) 

"Instructions for how to use the system." User Manual is essential for not only the users but also the customers to evaluate and use our application easily. 

***Todo's*:**

- [ ] Writing the User Manual
- [ ] Image insertion
- [ ] Documentation on wiki (new page)
- [ ] Documentation on the Report (add links)

***Reviewer*:** @burakmert236, @enginoguzhansenol 

***Task Deadline*:** 02.12.2022 16:00
***Review Deadline*:** 02.12.2022 20:00

**Comment by palahb** [comment]
[Mobile Manuals](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Manuals) are ready.
