### ISSUE TITLE
[Final Milestone] User Scenarios and Mockups 

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#540]
***Description*:**

**Part d.** in the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) 

Scenarios and mockups were created and they need to be documented on the Final Report.

See also, [Issue #518](https://github.com/bounswe/bounswe2022group5/issues/518) for the Scenarios created for Final Milestone Presentation specifically.

***Todo's*:**

- [x] Gathering the Scenarios and Mockups, doing some fixes maybe.
- [x] Editing the Sidebar. Tidy it up.
- [x] Documentation on the Report (add links)

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 02.12.2022 20:00
***Review Deadline*:** 02.12.2022 22:00

**Comment by canberkboun9** [comment]
- I have completed the documentation for Scenario 1 and 2 for Final Milestone. They pretty much cover all the core features of the application.
- I will merge them into one scenario and add that into the Final Report.

**Comment by canberkboun9** [comment]
- One can see: [User Scenarios and Mockups](https://github.com/bounswe/bounswe2022group5/wiki/User-Scenarios-and-Mockups)
- Also added the link to the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md#d-user-scenarios-and-mockups)

**Comment by canberkboun9** [comment]
- Added [work done](https://github.com/bounswe/bounswe2022group5/wiki/User-Scenarios-and-Mockups#work-done)
- Can be reviewed now.

**Comment by oguzhandemirelx** [comment]
Changes look good and tidy. Thanks for your effort.
