### ISSUE TITLE
[Final Milestone] FrontEnd User Manual

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#547]
***Description*:**

**Part a.** in the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) 

"Instructions for how to use the system." User Manual is essential for not only the users but also the customers to evaluate and use our application easily. 

This issue is mainly about the FrontEnd related parts of this requirement.

***Todo's*:**

- [x] Writing the User Manual
- [x] Image insertion
- [x] Documentation on wiki (new page)
- [x] Documentation on the Report (add links)

***Reviewer*:** @yavuuzsameet @burakmert236 

***Task Deadline*:** 02.12.2022 22:00
***Review Deadline*:** 02.12.2022 23:00

**Comment by Keremgunduz7** [comment]
Page is created in the wiki as [FrontEnd Manuals](https://github.com/bounswe/bounswe2022group5/wiki/FrontEnd-Manuals). It is going to be filled up together with @Oozankilic .

**Comment by Oozankilic** [comment]
The second half of the user manual is described.

**Comment by Keremgunduz7** [comment]
First Half of the User Manuel is described in the [Page](https://github.com/bounswe/bounswe2022group5/wiki/FrontEnd-Manuals). Need Review.
Thanks for your efforts @Oozankilic

**Comment by yavuuzsameet** [comment]
I think the links of the pages you have created need to be added to the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) page. ![Screenshot 2023-01-02 at 23 01 13](https://user-images.githubusercontent.com/73655554/210274049-8770c0e9-6ab4-4bcf-bb38-51895c0db637.png)

**Comment by Keremgunduz7** [comment]
Yes You're Right. Adding it right now. Thanks for the attention.

**Comment by yavuuzsameet** [comment]
Great work mate.
