### ISSUE TITLE
Practice App: Implementing API for Post

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#83]
**Description:**

The endpoints for the practice-app are determined in the [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2)
This issue stands for an endpoint to get all posts and create posts. In the meanwhile, an [external API](https://coronavirus.m.pipedream.net/) will be used to fetch the current COVID19 data where the post is sent from.
The initial models for the practice-app are pushed as mentioned in [issue #79](https://github.com/bounswe/bounswe2022group5/issues/79).

**Details for Post API and *todo's*:**
- [x] Check that given data is valid, i.e. existence of necessary parameters.
- [x] Determine the date of the post sent.
- [x] Using the [Coronavirus External API](https://coronavirus.m.pipedream.net/) if the country information exists.
- [x] Creating and saving posts, or getting posts.
- [x] Success or Error Response.
- [x] Postman Test.
- [x] Saving to Postman.
- [x] [Documentation](https://documenter.getpostman.com/view/20836438/UyxgJngP).

**Reviewers:** @mehmetemreakbulut @canberkboun9 

**Task Deadline:** 14.05.2022 16:00
**Review Deadline:** 14.05.2022 20:00

**Comment by yavuuzsameet** [comment]
In addition, the external API is going to be changed from ~~[Coronavirus External API](https://coronavirus.m.pipedream.net/)~~ to [Coronavirus COVID19 API](https://documenter.getpostman.com/view/10808728/SzS8rjbc). The necessary explanation is documented as a comment on the [corresponding issue](https://github.com/bounswe/bounswe2022group5/issues/78).

**Comment by yavuuzsameet** [comment]
All tasks are done. 

Quick recap:
- Firstly, the endpoints to GET and POST are created.
- After making sure that the endpoints are running well, the [external API](https://coronavirus.m.pipedream.net/) is added to the app.
- Then, the erroneous cases are handled by the try-catch mechanism.
- Finally, the [documentation](https://documenter.getpostman.com/view/20836438/UyxgJngP) is published.


Access the collection:

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/e34021c17a8dfebb6f3b?action=collection%2Fimport)

**Comment by yavuuzsameet** [comment]
Thanks for the quick review! I have also finished the UI of the app, and pushed the code. Can you also review it? I am now creating a pull request and linking with this issue. You can close the issue while merging.

**Comment by yavuuzsameet** [comment]
Postman documentation is updated after the change in the API. User info is no longer needed in the body when post endpoint is on the way.
